title: 'mahaloz.re'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/new.mahaloz.re"
url: "https://mahaloz.github.io"

header_pages:
  - index.md
  - about.md
  - tags.md

style: dark

footer: ''

# Build settings
markdown: kramdown

plugins:
- jekyll-seo-tag
