title: 'mahaloz.re'
description: "The blog of mahaloz: all things hacking and computer science included!"
baseurl: ""
url: "https://mahaloz.re"

header_pages:
  - index.md
  - about.md
  - tags.md

style: dark

footer: ''
favicon: assets/images/favicon.jpg

# Build settings
markdown: kramdown

plugins:
- jekyll-seo-tag
- jekyll-feed