title: 'mahaloz.re'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: ""
url: "https://mahaloz.re"

header_pages:
  - index.md
  - about.md
  - tags.md

style: dark

footer: ''
favicon: assets/images/favicon.jpg

# Build settings
markdown: kramdown

plugins:
- jekyll-seo-tag
